### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Tsjippy** [rene-hermenau/wp-staging-hooks#1]
I tried it to exclude folders but it does not work.

**Comment by rene-hermenau** [comment]
Thank you. We are checking this bug

**Comment by Tsjippy** [comment]
Any news?

**Comment by rene-hermenau** [comment]
Hi, should work now. See: https://github.com/wp-staging/wp-staging-hooks/commit/8770c7d5c3bd5ad6e5db7672b71d9311e7519755

The syntax to exclude certain plugins is slightly different.

If your issue is still not solved please give us a proper error description and let us know how we can reproduce it.

**Comment by Tsjippy** [comment]
its working now, but to prevent the logmessages I had to add the following:

file Logger.php line 152:
`if(is_array($message)){
    $messageString .= "[{$message["type"]}]-[{$message["date"]}] {$message["message"]}".PHP_EOL;
}`

file SearchReplace.php line 500:
`if ($key === '' || is_int($key) || ord($key[0]) === 0) {`
